subdir-ccflags-y += -Werror -I$(srctree)/drivers/misc/mediatek/include/mt-plat/
ccflags-y += -I$(srctree)/drivers/misc/mediatek/imgsensor/src/mt6735m/camera_hw


obj-$(CONFIG_BREATH_LEDS) := breath_leds.o
